name: Fuzz
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  slow:
    name: Slow large input tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@84f47b72e990ae11999fbe06c3efa449e943de60
    with:
      npm-task: test:slow
  fuzz:
    uses: paulmillr/cryptofuzz/.github/workflows/noble-commit-fuzz.yml@c4c2c6054b3545f7d6bb0f8608371a6a6f3c93fb
    with:
      ref: ${{ github.sha }}