name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: jsbt v0.5.1
    uses: paulmillr/jsbt/.github/workflows/release.yml@d156c5951d47d615d673d039aa03de6b9669449f
    permissions:
      contents: read
      id-token: write
