name: Run scheduled tests
on:
  schedule:
    - cron: '0 17 * * 1,4' # 17:00 bi-weekly (mon, thu)
  workflow_dispatch:
jobs:
  slow:
    name: Slow large input tests
<<<<<<< HEAD
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@78e04b481416536e0d4369a3c9f718be306491f8
||||||| parent of c334be9 (WIP)
=======
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@5320e209ca8cc9b1b0b569675e164bdd2a139d71
>>>>>>> c334be9 (WIP)
    with:
      npm-task: test:slow
